### ISSUE TITLE
Project Dead? @willyvmm?

### ISSUE THREAD

**Issue by thesnable** [willyvmm/mouSTer#22]
@willyvmm 

Is this Project dead? I got my mouster from retrohax yesterday, and the usb competition pro and the joystick from thec64 isnt working unfortunately.

I thought, you wanted to keep this updated?

Why dont release the source then?

**Comment by Afebriwyn** [comment]
If there is no more interest to continue the project, it would be a good idea to release it as open source in the hope that someone else will maintain and improve it.
I actually bought the mouster only because there was already a beta firmware with mousewheel support. Otherwise I would have bought the Micromys right away...

**Comment by willyvmm** [comment]
[https://github.com/willyvmm/mouSTer/issues/23#issue-1500949553 #](https://github.com/willyvmm/mouSTer/issues/23#issue-1500949553)
